# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-12 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LettersStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_read', models.BooleanField(default=False)),
                ('reading_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('sending_time', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('template', tinymce.models.HTMLField(blank=True, null=True)),
                ('users', models.ManyToManyField(blank=True, related_name='mailings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lettersstatus',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_status', to='subscriptions.Mailing'),
        ),
        migrations.AddField(
            model_name='lettersstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
