# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-14 08:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_been_read', models.BooleanField(default=False)),
                ('reading_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'letter_status',
                'verbose_name': 'LetterStatus',
                'verbose_name_plural': 'LettersStatus',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('sending_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'mailing',
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('html_data', models.TextField()),
                ('text_data', models.TextField()),
            ],
            options={
                'db_table': 'mail_template',
                'verbose_name': 'MailTemplate',
                'verbose_name_plural': 'MailTemplates',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailings', to='subscriptions.MailTemplate'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='mailings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letterstatus',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_status', to='subscriptions.Mailing'),
        ),
        migrations.AddField(
            model_name='letterstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='letterstatus',
            unique_together=set([('mailing', 'user')]),
        ),
    ]
