# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-11 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='mailings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lettersstatus',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_status', to='subscriptions.Mailing'),
        ),
        migrations.AddField(
            model_name='lettersstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
